modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="tweakium"
version="${version}"
displayName="Tweakium"
displayURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/"

credits=""
authors="SirEdvin"
description='''
A library for all of my peripheral mods, actually
'''

[[dependencies.tweakium]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.tweakium]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.tweakium]]
modId="broccolium"
mandatory=true
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"
