kotlin.code.style = official
org.gradle.jvmargs = -Xmx4G
org.gradle.warning.mode = all
org.gradle.daemon=false
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.20.1
# Mod Properties
broccoliumVersion = 1.4.5
tweakiumVersion = 1.4.5
peripheraliumVersion = 1.4.5
projectGroup = site.siredvin
