kotlin.code.style = official
org.gradle.jvmargs = -Xmx4G
org.gradle.warning.mode = all
org.gradle.daemon=false
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.20.1
# Mod Properties
broccoliumVersion = 2.0.0
testiariumVersion = 2.0.0
tweakiumVersion = 2.0.0
peripheraliumVersion = 2.0.0
projectGroup = site.siredvin
