kotlin.code.style = official
org.gradle.jvmargs = -Xmx4G
org.gradle.warning.mode = all
org.gradle.daemon=false
# Check these on https://fabricmc.net/develop/
minecraftVersion=1.21.1
# Mod Properties
broccoliumVersion = 1.0.0-rc.20
tweakiumVersion = 1.0.0-rc.20
peripheraliumVersion = 1.0.0-rc.20
projectGroup = site.siredvin
