modLoader="kotlinforforge"
loaderVersion="[5,)"

issueTrackerURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="peripheralium"
version="${file.jarVersion}"
displayName="Peripheralium"
displayURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/"

credits=""
authors="SirEdvin"
description='''
A basic mod for modding libs test
'''

[[dependencies.peripheralium]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="computercraft"
type="required"
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="broccolium"
type="required"
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="tweakium"
type="required"
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"
