modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MPL-2.0"

[[mods]]
modId="testiarium"
version="${file.jarVersion}"
displayName="Testiarium"
displayURL="https://github.com/SirEdvin/Minecraft-Modding-Libs"
authors="SirEdvin"
description='''Cross-loader GameTest framework.'''

[[dependencies.testiarium]]
modId="neoforge"
type="required"
versionRange="[${neoforgeVersion},)"
ordering="NONE"
side="BOTH"
