modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="peripheralium"
version="${version}"
displayName="Peripheralium"
displayURL="https://github.com/SirEdvin/Minecraft-Modding-Libs/"

credits=""
authors="SirEdvin"
description='''
A basic mod for modding libs test
'''

[[dependencies.peripheralium]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},48)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="broccolium"
mandatory=true
versionRange="[${broccoliumVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="tweakium"
mandatory=true
versionRange="[${tweakiumVersion},)"
ordering="NONE"
side="BOTH"
